// Legacy Strapi Configuration (commented for future reference)
// export const URL_BACKOFFICE_DOMAIN= process.env.NEXT_BACKOFFICE_DOMIAN ? process.env.NEXT_BACKOFFICE_DOMAIN : 'http://localhost:1337'

// Azure API Configuration
export const AZURE_API_URL = 'https://test-milesdashboard.azurewebsites.net/api/rest'
export const AZURE_BASE_URL = 'https://test-milesdashboard.azurewebsites.net/api'
export const AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NDQ5Y2I4MC00NDg4LTQyZDMtOTAyNi01Nzc4NGUzN2E2NWMiLCJqdGkiOiI0YTA2NjAzMzFlYzM1OTY5MDM1OGEzYjg3Mzk0OGI0MDdjZmU4ODU1NGIyYzk5YjQwYzgyNDY5NTA1ZTc3ZGVjMDVjNmFkNDQxNmVkODk4MSIsImlhdCI6MTcxODkwMjE1NC4yMzgxNjgsIm5iZiI6MTcxODkwMjE1NC4yMzgxNzMsImV4cCI6MTc1MDQzODE1NC4yMDczMzMsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.i_SB-dzodQ3pcG4XWiIiBzJDP8Qw2MfSfm6l05rgjB-Zb9nK-K4kZvV3B_Sxai91gi9UHjsgt1NAncdhUZIgNh0hK11JAyoqDnoedPxS0zWsRjiDsn4KGk_TwTY5jeZ-NJ9d2Y8Ulpb5oh2Ztk5dgOueDBWExSUQK3gmEvuHn5stLeRA7fOLMEFKJv03DGkXrhklOfPiTeakPmgCtIuin_-CY1vYisnZUTFtmPBoASzQX2bpUusKQfttCY4cGhcn4yCKvZ1UZrc5UlsGYkD0CTAO3f720WCgQgpn4NWV6TWE9BX7YeRQkMjelDQA2amxQxSSMV3nJJluT4DXVhSbuGGZjw-_VFeftR9QNAAH0cF9zpMkILZl-dc4RDFqj8smG13u-Kn_CMXADKw8wQhr0dhQf54TWHmr6ZiUfrHyDgHGcHA-CDAZt94nopGulai_jc3iYCWOEZcxS5dDA6Vq8ddNEgKnR80ihFddcsFo5LM8vjA6SWudvJlmu2EyVKhDFITvXeENoDqvq5Fkznxb85eacIR-YFJwZJOmk9BUB0HjQJG-eD9Uxez8SPHf6ky-cFJQapd5C1fK7ptLN7GC4K_Go1RVhcHYm4yqte5ARfQQV2ECAbLF4EMROS_j8Mk2yTou7IA5E8ry_Jtq2nlJHT360_7T7_i-OUSbP68ARhQ'

// DASHBOARD URL
export const URL_DASHBOARD= process.env.NEXT_BACKOFFICE_DOMIAN ? process.env.NEXT_BACKOFFICE_DOMIAN : 'https://test-milesdashboard.azurewebsites.net/api'
export const URL_BACKOFFICE_DOMAIN= process.env.URL_BACKOFFICE_DOMAIN ? process.env.URL_BACKOFFICE_DOMAIN : 'http://localhost:1337'